export const heatmaparrs = [
    {
        phage_id: 'TemPhD_cluster_10342',
        lysis: 6,
        integration: 9,
        replication: 8,
        tRNARelated: 2,
        regulation: 7,
        packaging: 4,
        assembly: 1,
        infection: 7,
        immune: 6,
        hypothetical: 8,
    },
    {
        phage_id: 'TemPhD_cluster_11412',
        lysis: 10,
        integration: 8,
        replication: 9,
        tRNARelated: 3,
        regulation: 2,
        packaging: 7,
        assembly: 9,
        infection: 5,
        immune: 5,
        hypothetical: 1,
    },
    {
        phage_id: 'TemPhD_cluster_22926',
        lysis: 3,
        integration: 8,
        replication: 5,
        tRNARelated: 0,
        regulation: 6,
        packaging: 2,
        assembly: 1,
        infection: 5,
        immune: 7,
        hypothetical: 10,
    },
    {
        phage_id: 'TemPhD_cluster_23888',
        lysis: 3,
        integration: 8,
        replication: 6,
        tRNARelated: 6,
        regulation: 6,
        packaging: 1,
        assembly: 5,
        infection: 5,
        immune: 6,
        hypothetical: 6,
    },
    {
        phage_id: 'TemPhD_cluster_26453',
        lysis: 3,
        integration: 0,
        replication: 1,
        tRNARelated: 2,
        regulation: 1,
        packaging: 1,
        assembly: 3,
        infection: 7,
        immune: 5,
        hypothetical: 4,
    },
    {
        phage_id: 'TemPhD_cluster_44301',
        lysis: 9,
        integration: 4,
        replication: 4,
        tRNARelated: 7,
        regulation: 1,
        packaging: 7,
        assembly: 5,
        infection: 1,
        immune: 9,
        hypothetical: 0,
    },
    {
        phage_id: 'TemPhD_cluster_63412',
        lysis: 3,
        integration: 8,
        replication: 9,
        tRNARelated: 4,
        regulation: 3,
        packaging: 2,
        assembly: 6,
        infection: 10,
        immune: 1,
        hypothetical: 3,
    },
    {
        phage_id: 'TemPhD_cluster_10339',
        lysis: 7,
        integration: 7,
        replication: 4,
        tRNARelated: 6,
        regulation: 7,
        packaging: 1,
        assembly: 10,
        infection: 4,
        immune: 3,
        hypothetical: 10,
    },
    {
        phage_id: 'TemPhD_cluster_11417',
        lysis: 6,
        integration: 0,
        replication: 0,
        tRNARelated: 8,
        regulation: 4,
        packaging: 8,
        assembly: 0,
        infection: 1,
        immune: 5,
        hypothetical: 2,
    },
    {
        phage_id: 'TemPhD_cluster_22927',
        lysis: 0,
        integration: 6,
        replication: 0,
        tRNARelated: 9,
        regulation: 7,
        packaging: 6,
        assembly: 5,
        infection: 2,
        immune: 2,
        hypothetical: 9,
    },
    {
        phage_id: 'TemPhD_cluster_22957',
        lysis: 8,
        integration: 5,
        replication: 0,
        tRNARelated: 10,
        regulation: 8,
        packaging: 3,
        assembly: 2,
        infection: 0,
        immune: 8,
        hypothetical: 2,
    },
    {
        phage_id: 'TemPhD_cluster_26449',
        lysis: 1,
        integration: 6,
        replication: 5,
        tRNARelated: 8,
        regulation: 8,
        packaging: 5,
        assembly: 1,
        infection: 9,
        immune: 7,
        hypothetical: 7,
    },
    {
        phage_id: 'TemPhD_cluster_26455',
        lysis: 8,
        integration: 5,
        replication: 9,
        tRNARelated: 1,
        regulation: 0,
        packaging: 3,
        assembly: 7,
        infection: 9,
        immune: 6,
        hypothetical: 8,
    },
    {
        phage_id: 'TemPhD_cluster_26479',
        lysis: 0,
        integration: 1,
        replication: 7,
        tRNARelated: 10,
        regulation: 6,
        packaging: 0,
        assembly: 2,
        infection: 5,
        immune: 6,
        hypothetical: 10,
    },
    {
        phage_id: 'TemPhD_cluster_52417',
        lysis: 6,
        integration: 6,
        replication: 5,
        tRNARelated: 1,
        regulation: 7,
        packaging: 4,
        assembly: 6,
        infection: 4,
        immune: 2,
        hypothetical: 7,
    },
    {
        phage_id: 'TemPhD_cluster_52288',
        lysis: 4,
        integration: 7,
        replication: 9,
        tRNARelated: 4,
        regulation: 8,
        packaging: 7,
        assembly: 0,
        infection: 5,
        immune: 7,
        hypothetical: 5,
    },
    {
        phage_id: 'TemPhD_cluster_52299',
        lysis: 0,
        integration: 6,
        replication: 9,
        tRNARelated: 9,
        regulation: 1,
        packaging: 7,
        assembly: 5,
        infection: 3,
        immune: 7,
        hypothetical: 1,
    },
    {
        phage_id: 'TemPhD_cluster_43961',
        lysis: 0,
        integration: 1,
        replication: 9,
        tRNARelated: 6,
        regulation: 0,
        packaging: 10,
        assembly: 7,
        infection: 5,
        immune: 6,
        hypothetical: 3,
    },
    {
        phage_id: 'TemPhD_cluster_52353',
        lysis: 6,
        integration: 3,
        replication: 9,
        tRNARelated: 9,
        regulation: 0,
        packaging: 3,
        assembly: 1,
        infection: 8,
        immune: 1,
        hypothetical: 4,
    },
    {
        phage_id: 'TemPhD_cluster_52523',
        lysis: 9,
        integration: 9,
        replication: 6,
        tRNARelated: 1,
        regulation: 10,
        packaging: 6,
        assembly: 2,
        infection: 4,
        immune: 2,
        hypothetical: 8,
    },
    {
        phage_id: 'TemPhD_cluster_52470',
        lysis: 7,
        integration: 0,
        replication: 1,
        tRNARelated: 5,
        regulation: 3,
        packaging: 8,
        assembly: 9,
        infection: 1,
        immune: 5,
        hypothetical: 0,
    },
    {
        phage_id: 'uvig_370648',
        lysis: 2,
        integration: 4,
        replication: 7,
        tRNARelated: 7,
        regulation: 8,
        packaging: 9,
        assembly: 3,
        infection: 4,
        immune: 8,
        hypothetical: 0,
    },
    {
        phage_id: 'TemPhD_cluster_52486',
        lysis: 5,
        integration: 2,
        replication: 10,
        tRNARelated: 9,
        regulation: 1,
        packaging: 0,
        assembly: 1,
        infection: 3,
        immune: 0,
        hypothetical: 4,
    },
    {
        phage_id: 'TemPhD_cluster_7327',
        lysis: 5,
        integration: 2,
        replication: 7,
        tRNARelated: 6,
        regulation: 4,
        packaging: 1,
        assembly: 3,
        infection: 10,
        immune: 3,
        hypothetical: 7,
    },
    {
        phage_id: 'TemPhD_cluster_7333',
        lysis: 10,
        integration: 1,
        replication: 3,
        tRNARelated: 3,
        regulation: 0,
        packaging: 9,
        assembly: 8,
        infection: 8,
        immune: 0,
        hypothetical: 5,
    },
    {
        phage_id: 'TemPhD_cluster_63439',
        lysis: 2,
        integration: 5,
        replication: 8,
        tRNARelated: 4,
        regulation: 4,
        packaging: 4,
        assembly: 6,
        infection: 6,
        immune: 5,
        hypothetical: 6,
    },
    {
        phage_id: 'TemPhD_cluster_43959',
        lysis: 9,
        integration: 3,
        replication: 7,
        tRNARelated: 6,
        regulation: 6,
        packaging: 10,
        assembly: 5,
        infection: 9,
        immune: 9,
        hypothetical: 8,
    },
    {
        phage_id: 'TemPhD_cluster_44199',
        lysis: 9,
        integration: 3,
        replication: 10,
        tRNARelated: 3,
        regulation: 6,
        packaging: 5,
        assembly: 7,
        infection: 5,
        immune: 8,
        hypothetical: 1,
    },
    {
        phage_id: 'TemPhD_cluster_44360',
        lysis: 6,
        integration: 2,
        replication: 10,
        tRNARelated: 8,
        regulation: 1,
        packaging: 5,
        assembly: 10,
        infection: 8,
        immune: 8,
        hypothetical: 7,
    },
    {
        phage_id: 'TemPhD_cluster_22956',
        lysis: 7,
        integration: 6,
        replication: 5,
        tRNARelated: 10,
        regulation: 4,
        packaging: 0,
        assembly: 2,
        infection: 8,
        immune: 8,
        hypothetical: 1,
    },
    {
        phage_id: 'TemPhD_cluster_18168',
        lysis: 4,
        integration: 2,
        replication: 9,
        tRNARelated: 1,
        regulation: 6,
        packaging: 7,
        assembly: 0,
        infection: 1,
        immune: 2,
        hypothetical: 6,
    },
    {
        phage_id: 'TemPhD_cluster_10334',
        lysis: 3,
        integration: 7,
        replication: 2,
        tRNARelated: 7,
        regulation: 2,
        packaging: 0,
        assembly: 4,
        infection: 6,
        immune: 6,
        hypothetical: 1,
    },
    {
        phage_id: 'TemPhD_cluster_10335',
        lysis: 5,
        integration: 10,
        replication: 7,
        tRNARelated: 1,
        regulation: 3,
        packaging: 3,
        assembly: 8,
        infection: 6,
        immune: 9,
        hypothetical: 10,
    },
    {
        phage_id: 'TemPhD_cluster_10336',
        lysis: 6,
        integration: 5,
        replication: 4,
        tRNARelated: 9,
        regulation: 9,
        packaging: 4,
        assembly: 6,
        infection: 6,
        immune: 9,
        hypothetical: 3,
    },
    {
        phage_id: 'TemPhD_cluster_10337',
        lysis: 1,
        integration: 0,
        replication: 5,
        tRNARelated: 0,
        regulation: 5,
        packaging: 7,
        assembly: 8,
        infection: 7,
        immune: 2,
        hypothetical: 5,
    },
    {
        phage_id: 'TemPhD_cluster_10338',
        lysis: 3,
        integration: 5,
        replication: 8,
        tRNARelated: 10,
        regulation: 4,
        packaging: 9,
        assembly: 9,
        infection: 4,
        immune: 9,
        hypothetical: 4,
    },
    {
        phage_id: 'TemPhD_cluster_10340',
        lysis: 3,
        integration: 10,
        replication: 3,
        tRNARelated: 10,
        regulation: 8,
        packaging: 4,
        assembly: 4,
        infection: 4,
        immune: 10,
        hypothetical: 7,
    },
    {
        phage_id: 'TemPhD_cluster_10341',
        lysis: 1,
        integration: 4,
        replication: 3,
        tRNARelated: 10,
        regulation: 2,
        packaging: 0,
        assembly: 3,
        infection: 2,
        immune: 8,
        hypothetical: 1,
    },
    {
        phage_id: 'TemPhD_cluster_10343',
        lysis: 6,
        integration: 9,
        replication: 10,
        tRNARelated: 8,
        regulation: 9,
        packaging: 9,
        assembly: 9,
        infection: 3,
        immune: 5,
        hypothetical: 9,
    },
    {
        phage_id: 'TemPhD_cluster_10344',
        lysis: 5,
        integration: 10,
        replication: 3,
        tRNARelated: 0,
        regulation: 6,
        packaging: 2,
        assembly: 1,
        infection: 3,
        immune: 9,
        hypothetical: 2,
    },
    {
        phage_id: 'TemPhD_cluster_10345',
        lysis: 3,
        integration: 6,
        replication: 7,
        tRNARelated: 2,
        regulation: 7,
        packaging: 6,
        assembly: 2,
        infection: 9,
        immune: 1,
        hypothetical: 5,
    },
    {
        phage_id: 'TemPhD_cluster_11405',
        lysis: 1,
        integration: 9,
        replication: 6,
        tRNARelated: 1,
        regulation: 5,
        packaging: 1,
        assembly: 3,
        infection: 0,
        immune: 9,
        hypothetical: 2,
    },
    {
        phage_id: 'TemPhD_cluster_11406',
        lysis: 4,
        integration: 0,
        replication: 3,
        tRNARelated: 7,
        regulation: 10,
        packaging: 1,
        assembly: 5,
        infection: 5,
        immune: 0,
        hypothetical: 1,
    },
    {
        phage_id: 'TemPhD_cluster_11407',
        lysis: 3,
        integration: 0,
        replication: 8,
        tRNARelated: 8,
        regulation: 4,
        packaging: 0,
        assembly: 8,
        infection: 5,
        immune: 9,
        hypothetical: 0,
    },
    {
        phage_id: 'TemPhD_cluster_11408',
        lysis: 9,
        integration: 8,
        replication: 0,
        tRNARelated: 2,
        regulation: 10,
        packaging: 5,
        assembly: 6,
        infection: 3,
        immune: 3,
        hypothetical: 0,
    },
    {
        phage_id: 'TemPhD_cluster_11409',
        lysis: 2,
        integration: 9,
        replication: 0,
        tRNARelated: 4,
        regulation: 10,
        packaging: 5,
        assembly: 5,
        infection: 7,
        immune: 1,
        hypothetical: 9,
    },
    {
        phage_id: 'TemPhD_cluster_11410',
        lysis: 10,
        integration: 10,
        replication: 4,
        tRNARelated: 3,
        regulation: 3,
        packaging: 3,
        assembly: 9,
        infection: 2,
        immune: 8,
        hypothetical: 6,
    },
    {
        phage_id: 'TemPhD_cluster_11411',
        lysis: 2,
        integration: 1,
        replication: 10,
        tRNARelated: 0,
        regulation: 0,
        packaging: 1,
        assembly: 4,
        infection: 8,
        immune: 7,
        hypothetical: 7,
    },
    {
        phage_id: 'TemPhD_cluster_11413',
        lysis: 6,
        integration: 8,
        replication: 7,
        tRNARelated: 10,
        regulation: 7,
        packaging: 4,
        assembly: 10,
        infection: 10,
        immune: 9,
        hypothetical: 2,
    },
    {
        phage_id: 'TemPhD_cluster_11414',
        lysis: 5,
        integration: 9,
        replication: 3,
        tRNARelated: 2,
        regulation: 7,
        packaging: 10,
        assembly: 2,
        infection: 7,
        immune: 3,
        hypothetical: 2,
    },
    {
        phage_id: 'TemPhD_cluster_11415',
        lysis: 7,
        integration: 6,
        replication: 10,
        tRNARelated: 5,
        regulation: 9,
        packaging: 1,
        assembly: 5,
        infection: 7,
        immune: 6,
        hypothetical: 1,
    },
    {
        phage_id: 'TemPhD_cluster_11416',
        lysis: 7,
        integration: 5,
        replication: 1,
        tRNARelated: 9,
        regulation: 4,
        packaging: 3,
        assembly: 9,
        infection: 7,
        immune: 9,
        hypothetical: 10,
    },
    {
        phage_id: 'TemPhD_cluster_11418',
        lysis: 6,
        integration: 7,
        replication: 5,
        tRNARelated: 9,
        regulation: 7,
        packaging: 7,
        assembly: 2,
        infection: 3,
        immune: 2,
        hypothetical: 10,
    },
    {
        phage_id: 'TemPhD_cluster_11419',
        lysis: 6,
        integration: 5,
        replication: 4,
        tRNARelated: 10,
        regulation: 6,
        packaging: 7,
        assembly: 8,
        infection: 3,
        immune: 9,
        hypothetical: 4,
    },
    {
        phage_id: 'TemPhD_cluster_20044',
        lysis: 1,
        integration: 1,
        replication: 8,
        tRNARelated: 2,
        regulation: 10,
        packaging: 9,
        assembly: 4,
        infection: 6,
        immune: 5,
        hypothetical: 3,
    },
    {
        phage_id: 'TemPhD_cluster_20045',
        lysis: 10,
        integration: 1,
        replication: 3,
        tRNARelated: 2,
        regulation: 8,
        packaging: 5,
        assembly: 6,
        infection: 9,
        immune: 0,
        hypothetical: 5,
    },
    {
        phage_id: 'TemPhD_cluster_21319',
        lysis: 6,
        integration: 4,
        replication: 4,
        tRNARelated: 4,
        regulation: 1,
        packaging: 2,
        assembly: 3,
        infection: 1,
        immune: 1,
        hypothetical: 2,
    },
    {
        phage_id: 'TemPhD_cluster_22924',
        lysis: 7,
        integration: 1,
        replication: 5,
        tRNARelated: 4,
        regulation: 9,
        packaging: 6,
        assembly: 1,
        infection: 1,
        immune: 5,
        hypothetical: 5,
    },
    {
        phage_id: 'TemPhD_cluster_22928',
        lysis: 4,
        integration: 2,
        replication: 0,
        tRNARelated: 7,
        regulation: 9,
        packaging: 2,
        assembly: 9,
        infection: 7,
        immune: 9,
        hypothetical: 6,
    },
    {
        phage_id: 'TemPhD_cluster_23890',
        lysis: 2,
        integration: 1,
        replication: 6,
        tRNARelated: 10,
        regulation: 6,
        packaging: 0,
        assembly: 0,
        infection: 2,
        immune: 0,
        hypothetical: 5,
    },
    {
        phage_id: 'TemPhD_cluster_23892',
        lysis: 4,
        integration: 1,
        replication: 10,
        tRNARelated: 0,
        regulation: 9,
        packaging: 3,
        assembly: 9,
        infection: 1,
        immune: 2,
        hypothetical: 0,
    },
    {
        phage_id: 'TemPhD_cluster_23894',
        lysis: 8,
        integration: 0,
        replication: 0,
        tRNARelated: 1,
        regulation: 2,
        packaging: 10,
        assembly: 6,
        infection: 3,
        immune: 6,
        hypothetical: 6,
    },
    {
        phage_id: 'TemPhD_cluster_22958',
        lysis: 5,
        integration: 10,
        replication: 8,
        tRNARelated: 1,
        regulation: 4,
        packaging: 10,
        assembly: 4,
        infection: 8,
        immune: 7,
        hypothetical: 3,
    },
    {
        phage_id: 'TemPhD_cluster_26448',
        lysis: 3,
        integration: 0,
        replication: 0,
        tRNARelated: 3,
        regulation: 9,
        packaging: 3,
        assembly: 6,
        infection: 8,
        immune: 6,
        hypothetical: 7,
    },
    {
        phage_id: 'TemPhD_cluster_26450',
        lysis: 1,
        integration: 3,
        replication: 10,
        tRNARelated: 6,
        regulation: 2,
        packaging: 4,
        assembly: 10,
        infection: 1,
        immune: 3,
        hypothetical: 2,
    },
    {
        phage_id: 'TemPhD_cluster_26475',
        lysis: 9,
        integration: 9,
        replication: 9,
        tRNARelated: 9,
        regulation: 10,
        packaging: 1,
        assembly: 8,
        infection: 10,
        immune: 0,
        hypothetical: 1,
    },
    {
        phage_id: 'TemPhD_cluster_26451',
        lysis: 9,
        integration: 1,
        replication: 5,
        tRNARelated: 7,
        regulation: 4,
        packaging: 0,
        assembly: 9,
        infection: 9,
        immune: 9,
        hypothetical: 5,
    },
    {
        phage_id: 'TemPhD_cluster_26452',
        lysis: 6,
        integration: 7,
        replication: 10,
        tRNARelated: 8,
        regulation: 7,
        packaging: 9,
        assembly: 4,
        infection: 1,
        immune: 0,
        hypothetical: 1,
    },
    {
        phage_id: 'TemPhD_cluster_28403',
        lysis: 6,
        integration: 5,
        replication: 9,
        tRNARelated: 9,
        regulation: 9,
        packaging: 2,
        assembly: 0,
        infection: 0,
        immune: 9,
        hypothetical: 0,
    },
    {
        phage_id: 'TemPhD_cluster_30677',
        lysis: 5,
        integration: 4,
        replication: 2,
        tRNARelated: 7,
        regulation: 4,
        packaging: 6,
        assembly: 2,
        infection: 5,
        immune: 9,
        hypothetical: 9,
    },
    {
        phage_id: 'TemPhD_cluster_30678',
        lysis: 2,
        integration: 8,
        replication: 6,
        tRNARelated: 2,
        regulation: 9,
        packaging: 1,
        assembly: 8,
        infection: 2,
        immune: 6,
        hypothetical: 4,
    },
    {
        phage_id: 'TemPhD_cluster_30679',
        lysis: 9,
        integration: 0,
        replication: 10,
        tRNARelated: 1,
        regulation: 2,
        packaging: 8,
        assembly: 8,
        infection: 9,
        immune: 9,
        hypothetical: 3,
    },
    {
        phage_id: 'TemPhD_cluster_30680',
        lysis: 8,
        integration: 7,
        replication: 5,
        tRNARelated: 8,
        regulation: 10,
        packaging: 1,
        assembly: 10,
        infection: 0,
        immune: 5,
        hypothetical: 8,
    },
    {
        phage_id: 'TemPhD_cluster_43960',
        lysis: 6,
        integration: 8,
        replication: 3,
        tRNARelated: 5,
        regulation: 4,
        packaging: 0,
        assembly: 0,
        infection: 3,
        immune: 5,
        hypothetical: 4,
    },
    {
        phage_id: 'TemPhD_cluster_30747',
        lysis: 8,
        integration: 1,
        replication: 4,
        tRNARelated: 10,
        regulation: 6,
        packaging: 10,
        assembly: 10,
        infection: 5,
        immune: 10,
        hypothetical: 4,
    },
    {
        phage_id: 'TemPhD_cluster_38162',
        lysis: 4,
        integration: 1,
        replication: 9,
        tRNARelated: 7,
        regulation: 6,
        packaging: 7,
        assembly: 1,
        infection: 4,
        immune: 10,
        hypothetical: 9,
    },
    {
        phage_id: 'TemPhD_cluster_44037',
        lysis: 2,
        integration: 1,
        replication: 2,
        tRNARelated: 4,
        regulation: 2,
        packaging: 9,
        assembly: 6,
        infection: 10,
        immune: 6,
        hypothetical: 0,
    },
    {
        phage_id: 'TemPhD_cluster_33790',
        lysis: 8,
        integration: 4,
        replication: 7,
        tRNARelated: 5,
        regulation: 10,
        packaging: 0,
        assembly: 8,
        infection: 4,
        immune: 8,
        hypothetical: 9,
    },
    {
        phage_id: 'TemPhD_cluster_33806',
        lysis: 6,
        integration: 9,
        replication: 9,
        tRNARelated: 8,
        regulation: 7,
        packaging: 2,
        assembly: 5,
        infection: 0,
        immune: 5,
        hypothetical: 10,
    },
    {
        phage_id: 'TemPhD_cluster_38107',
        lysis: 5,
        integration: 5,
        replication: 0,
        tRNARelated: 2,
        regulation: 3,
        packaging: 6,
        assembly: 1,
        infection: 3,
        immune: 0,
        hypothetical: 6,
    },
    {
        phage_id: 'TemPhD_cluster_44254',
        lysis: 9,
        integration: 6,
        replication: 10,
        tRNARelated: 10,
        regulation: 10,
        packaging: 0,
        assembly: 10,
        infection: 7,
        immune: 7,
        hypothetical: 5,
    },
    {
        phage_id: 'TemPhD_cluster_44300',
        lysis: 9,
        integration: 1,
        replication: 6,
        tRNARelated: 4,
        regulation: 5,
        packaging: 2,
        assembly: 8,
        infection: 2,
        immune: 5,
        hypothetical: 0,
    },
    {
        phage_id: 'TemPhD_cluster_44303',
        lysis: 7,
        integration: 10,
        replication: 8,
        tRNARelated: 0,
        regulation: 7,
        packaging: 9,
        assembly: 3,
        infection: 6,
        immune: 4,
        hypothetical: 7,
    },
    {
        phage_id: 'TemPhD_cluster_44317',
        lysis: 5,
        integration: 8,
        replication: 1,
        tRNARelated: 1,
        regulation: 1,
        packaging: 2,
        assembly: 6,
        infection: 2,
        immune: 2,
        hypothetical: 5,
    },
    {
        phage_id: 'TemPhD_cluster_44362',
        lysis: 7,
        integration: 7,
        replication: 2,
        tRNARelated: 3,
        regulation: 7,
        packaging: 6,
        assembly: 0,
        infection: 10,
        immune: 8,
        hypothetical: 3,
    },
    {
        phage_id: 'TemPhD_cluster_63144',
        lysis: 2,
        integration: 7,
        replication: 2,
        tRNARelated: 0,
        regulation: 0,
        packaging: 8,
        assembly: 2,
        infection: 0,
        immune: 8,
        hypothetical: 9,
    },
    {
        phage_id: 'TemPhD_cluster_63074',
        lysis: 0,
        integration: 10,
        replication: 10,
        tRNARelated: 7,
        regulation: 4,
        packaging: 0,
        assembly: 9,
        infection: 4,
        immune: 6,
        hypothetical: 1,
    },
    {
        phage_id: 'TemPhD_cluster_63257',
        lysis: 8,
        integration: 5,
        replication: 3,
        tRNARelated: 6,
        regulation: 6,
        packaging: 6,
        assembly: 3,
        infection: 5,
        immune: 0,
        hypothetical: 4,
    },
    {
        phage_id: 'TemPhD_cluster_63406',
        lysis: 10,
        integration: 4,
        replication: 1,
        tRNARelated: 5,
        regulation: 0,
        packaging: 6,
        assembly: 4,
        infection: 6,
        immune: 0,
        hypothetical: 3,
    },
    {
        phage_id: 'TemPhD_cluster_7322',
        lysis: 5,
        integration: 2,
        replication: 3,
        tRNARelated: 6,
        regulation: 7,
        packaging: 0,
        assembly: 8,
        infection: 0,
        immune: 9,
        hypothetical: 6,
    },
    {
        phage_id: 'TemPhD_cluster_7323',
        lysis: 5,
        integration: 3,
        replication: 10,
        tRNARelated: 9,
        regulation: 7,
        packaging: 2,
        assembly: 3,
        infection: 3,
        immune: 8,
        hypothetical: 2,
    },
    {
        phage_id: 'TemPhD_cluster_7324',
        lysis: 5,
        integration: 8,
        replication: 2,
        tRNARelated: 4,
        regulation: 2,
        packaging: 5,
        assembly: 1,
        infection: 1,
        immune: 10,
        hypothetical: 9,
    },
    {
        phage_id: 'TemPhD_cluster_7325',
        lysis: 2,
        integration: 4,
        replication: 8,
        tRNARelated: 8,
        regulation: 4,
        packaging: 6,
        assembly: 0,
        infection: 2,
        immune: 9,
        hypothetical: 2,
    },
    {
        phage_id: 'TemPhD_cluster_7326',
        lysis: 8,
        integration: 3,
        replication: 3,
        tRNARelated: 4,
        regulation: 10,
        packaging: 4,
        assembly: 0,
        infection: 0,
        immune: 8,
        hypothetical: 0,
    },
    {
        phage_id: 'TemPhD_cluster_7328',
        lysis: 7,
        integration: 2,
        replication: 5,
        tRNARelated: 10,
        regulation: 5,
        packaging: 7,
        assembly: 7,
        infection: 7,
        immune: 9,
        hypothetical: 6,
    },
    {
        phage_id: 'TemPhD_cluster_7329',
        lysis: 3,
        integration: 4,
        replication: 1,
        tRNARelated: 1,
        regulation: 8,
        packaging: 2,
        assembly: 3,
        infection: 9,
        immune: 8,
        hypothetical: 2,
    },
    {
        phage_id: 'TemPhD_cluster_7330',
        lysis: 6,
        integration: 10,
        replication: 5,
        tRNARelated: 5,
        regulation: 3,
        packaging: 2,
        assembly: 8,
        infection: 8,
        immune: 2,
        hypothetical: 9,
    },
    {
        phage_id: 'TemPhD_cluster_7331',
        lysis: 3,
        integration: 4,
        replication: 3,
        tRNARelated: 5,
        regulation: 10,
        packaging: 2,
        assembly: 7,
        infection: 2,
        immune: 2,
        hypothetical: 9,
    },
    {
        phage_id: 'TemPhD_cluster_7332',
        lysis: 1,
        integration: 5,
        replication: 3,
        tRNARelated: 9,
        regulation: 10,
        packaging: 1,
        assembly: 7,
        infection: 7,
        immune: 3,
        hypothetical: 8,
    },
    {
        phage_id: 'TemPhD_cluster_7334',
        lysis: 0,
        integration: 6,
        replication: 3,
        tRNARelated: 8,
        regulation: 3,
        packaging: 4,
        assembly: 7,
        infection: 8,
        immune: 4,
        hypothetical: 1,
    },
    {
        phage_id: 'TemPhD_cluster_7335',
        lysis: 7,
        integration: 8,
        replication: 9,
        tRNARelated: 4,
        regulation: 1,
        packaging: 0,
        assembly: 7,
        infection: 7,
        immune: 9,
        hypothetical: 6,
    },
    {
        phage_id: 'TemPhD_cluster_7336',
        lysis: 3,
        integration: 7,
        replication: 2,
        tRNARelated: 5,
        regulation: 7,
        packaging: 3,
        assembly: 1,
        infection: 4,
        immune: 3,
        hypothetical: 8,
    },
    {
        phage_id: 'TemPhD_cluster_7337',
        lysis: 4,
        integration: 5,
        replication: 8,
        tRNARelated: 10,
        regulation: 5,
        packaging: 9,
        assembly: 0,
        infection: 6,
        immune: 7,
        hypothetical: 2,
    },
    {
        phage_id: 'TemPhD_cluster_7338',
        lysis: 7,
        integration: 9,
        replication: 3,
        tRNARelated: 4,
        regulation: 3,
        packaging: 1,
        assembly: 7,
        infection: 3,
        immune: 8,
        hypothetical: 8,
    },
    {
        phage_id: 'TemPhD_cluster_7339',
        lysis: 6,
        integration: 2,
        replication: 9,
        tRNARelated: 8,
        regulation: 3,
        packaging: 7,
        assembly: 0,
        infection: 6,
        immune: 2,
        hypothetical: 7,
    },
    {
        phage_id: 'TemPhD_cluster_7340',
        lysis: 1,
        integration: 5,
        replication: 5,
        tRNARelated: 4,
        regulation: 7,
        packaging: 9,
        assembly: 5,
        infection: 5,
        immune: 9,
        hypothetical: 7,
    },
    {
        phage_id: 'TemPhD_cluster_7341',
        lysis: 9,
        integration: 7,
        replication: 3,
        tRNARelated: 10,
        regulation: 7,
        packaging: 8,
        assembly: 6,
        infection: 5,
        immune: 2,
        hypothetical: 6,
    },
]

export const TypeDict = {
    lysis: { color: '#ec364e', abbr: 'Lys', name: 'Lysis' },
    integration: { color: '#9dc6e7', abbr: 'Int', name: 'Integration' },
    replication: { color: '#0FF0BF', abbr: 'Rep', name: 'Replication' },
    tRNA: { color: '#90ed7d ', abbr: 'tRNA-related', name: 'tRNA-related' },
    regulation: { color: '#445d8f', abbr: 'Reg', name: 'Regulation' },
    packaging: { color: '#9343f0', abbr: 'Pkg', name: 'Packaging' },
    assembly: { color: '#45bf43', abbr: 'Asm', name: 'Assembly' },
    infection: { color: '#5490F8', abbr: 'Inf', name: 'Infection' },
    immune: { color: '#DF3AD2', abbr: 'Imm', name: 'Immune' },
    mix: { color: '#f9ee07', abbr: 'Mix', name: 'Mix' },
    hypothetical: { color: '#29cbce', abbr: 'Hyp', name: 'Hypothetical' },
    unsorted: { color: '#ffa235', abbr: 'Uns', name: 'Unsorted' },
    tRNARelated: { color: '#90ed7d ', abbr: 'tRNA-related', name: 'tRNA-related' },
}
