export const datasetList = [
    'PLSDB',
    'IMG-PR',
    'COMPASS',
    'GenBank',
    'RefSeq',
    'EMBL',
    'Kraken2',
    'DDBJ',
    'TPA',
]

export const datasetDict = [
    {
        label: 'ALL',
        value: -1,
    },
    {
        label: 'PLSDB',
        value: 0,
    },
    {
        label: 'IMG-PR',
        value: 1,
    },
    {
        label: 'COMPASS',
        value: 2,
    },
    {
        label: 'GenBank',
        value: 3,
    },
    {
        label: 'RefSeq',
        value: 4,
    },
    {
        label: 'EMBL',
        value: 5,
    },
    {
        label: 'Kraken2',
        value: 6,
    },
    {
        label: 'DDBJ',
        value: 7,
    },
    {
        label: 'TPA',
        value: 8,
    },
]

export const COGCategoryList = [
    'Translation, ribosomal structure and biogenesis',
    'RNA processing and modification',
    'Transcription',
    'Replication, recombination and repair',
    'Chromatin structure and dynamics',
    'Cell cycle control, cell division, chromosome partitioning',
    'Nuclear structure',
    'Defense mechanisms',
    'Signal transduction mechanisms',
    'Cell wall/membrane/envelope biogenesis',
    'Cell motility',
    'Cytoskeleton',
    'Extracellular structures',
    'Intracellular trafficking, secretion, and vesicular transport',
    'Posttranslational modification, protein turnover, chaperones',
    'Mobilome: prophages, transposons',
    'Energy production and conversion',
    'Carbohydrate transport and metabolism',
    'Amino acid transport and metabolism',
    'Nucleotide transport and metabolism',
    'Coenzyme transport and metabolism',
    'Lipid transport and metabolism',
    'Inorganic ion transport and metabolism',
    'Secondary metabolites biosynthesis, transport and catabolism',
    'General function prediction only',
    'Function unknown',
]

export const COGCategoryDict = {
    J: 'Translation, ribosomal structure and biogenesis',
    A: 'RNA processing and modification',
    K: 'Transcription',
    L: 'Replication, recombination and repair',
    B: 'Chromatin structure and dynamics',
    D: 'Cell cycle control, cell division, chromosome partitioning',
    Y: 'Nuclear structure',
    V: 'Defense mechanisms',
    T: 'Signal transduction mechanisms',
    M: 'Cell wall/membrane/envelope biogenesis',
    N: 'Cell motility',
    Z: 'Cytoskeleton',
    W: 'Extracellular structures',
    U: 'Intracellular trafficking, secretion, and vesicular transport',
    O: 'Posttranslational modification, protein turnover, chaperones',
    X: 'Mobilome: prophages, transposons',
    C: 'Energy production and conversion',
    G: 'Carbohydrate transport and metabolism',
    E: 'Amino acid transport and metabolism',
    F: 'Nucleotide transport and metabolism',
    H: 'Coenzyme transport and metabolism',
    I: 'Lipid transport and metabolism',
    P: 'Inorganic ion transport and metabolism',
    Q: 'Secondary metabolites biosynthesis, transport and catabolism',
    R: 'General function prediction only',
    S: 'Function unknown',
    '': '-',
}
